/**
 * The simulation's stand-in for the app's WebSocket handler module.
 *
 * The real one is generated by the build and reached through the `WS_HANDLER`
 * specifier that ws-handler-bridge.js imports; sim-loader.mjs points that
 * specifier here so the REAL dispatch can run headless under the simulator.
 * Same live-bindings shape as the unit tests' stub: a module namespace is
 * immutable, but reading `wsModule.subscribe` follows the exported binding,
 * which is what lets each sim run install its own hooks.
 */

/** @type {any} */ export let subscribe;
/** @type {any} */ export let subscribeBatch;
/** @type {any} */ export let unsubscribe;
/** @type {any} */ export let open;
/** @type {any} */ export let message;
/** @type {any} */ export let close;
/** @type {any} */ export let drain;
/** @type {any} */ export let upgrade;
/** @type {any} */ export let resume;
/** @type {any} */ export let init;
/** @type {any} */ export let shutdown;

/**
 * Install (or clear) the hooks for the next sim run. Every export not named
 * in `hooks` resets to undefined, so one run's hooks can never leak into the
 * next seed's.
 *
 * @param {Record<string, any>} [hooks]
 */
export function __setSimHooks(hooks = {}) {
	subscribe = hooks.subscribe;
	subscribeBatch = hooks.subscribeBatch;
	unsubscribe = hooks.unsubscribe;
	open = hooks.open;
	message = hooks.message;
	close = hooks.close;
	drain = hooks.drain;
	upgrade = hooks.upgrade;
	resume = hooks.resume;
	init = hooks.init;
	shutdown = hooks.shutdown;
}
